namespace TableStorage.SourceGenerators;
internal static class Header
{
    public const string Value = """
        // Generated by TableStorage 5.0.0 \\

        #nullable disable
        #pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
        #pragma warning disable CS8669 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.


        """;
}
