<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- 👇 We don't want to reference the source generator dll directly in consuming projects -->
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<IsPackable>false</IsPackable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>

	<ItemGroup>
	  <AdditionalFiles Include="AnalyzerReleases.*.md" />
	</ItemGroup>

	<!-- This ensures the library will be packaged as a source generator when we use `dotnet pack` -->
	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>
</Project>
