<Project>
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
	</PropertyGroup>
	
	<PropertyGroup>
		<Company>Liesel Thuriot</Company>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/LieselThuriot/TableStorage</RepositoryUrl>
		<PackageProjectUrl>https://github.com/LieselThuriot/TableStorage</PackageProjectUrl>
		<Copyright>Liesel Thuriot</Copyright>
		<Authors>Liesel Thuriot</Authors>
	</PropertyGroup>

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedResources>true</EmbedUntrackedResources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSource>true</IncludeSource>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageOutputPath>$(SolutionDir)/Packages</PackageOutputPath>
	</PropertyGroup>
	
	<PropertyGroup>
		<MajorMinorVersion>6.0</MajorMinorVersion>
		<NextMajorVersion>$([MSBuild]::Add($([System.String]::new('$(MajorMinorVersion)').Split('.')[0]), 1)).0</NextMajorVersion>
		<NextMajorMinorVersion>$([System.String]::new('$(MajorMinorVersion)').Split('.')[0]).$([MSBuild]::Add($([System.String]::new('$(MajorMinorVersion)').Split('.')[1]), 1))</NextMajorMinorVersion>
		<VersionSuffix>preview-03</VersionSuffix>
		<DashedVersionSuffix Condition="'$(VersionSuffix)' != ''">-$(VersionSuffix)</DashedVersionSuffix>
		<MinDashedVersionSuffix Condition="'$(VersionSuffix)' != ''">-preview.1</MinDashedVersionSuffix>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AsyncFixer" Version="2.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Target Name="UseExplicitPackageVersions" BeforeTargets="GenerateNuspec">
		<ItemGroup>
			<_ProjectReferencesWithVersions Condition="'%(FullPath)' != ''">
				<PackageVersion>@(ProjectReference->'%(PackageVersion)')</PackageVersion>
			</_ProjectReferencesWithVersions>
			<_ProjectReferencesWithVersions Condition="'%(Identity)' != '' And '%(PackageVersion)' != ''">
				<ProjectVersion>$([System.String]::new('%(PackageVersion)').Replace('~',%(ProjectVersion)).Replace('^',$(MajorMinorVersion)$(MinDashedVersionSuffix)).Replace('`',$(NextMajorMinorVersion)).Replace('$',$(NextMajorVersion)))</ProjectVersion>
			</_ProjectReferencesWithVersions>
		</ItemGroup>
	</Target>
</Project>