<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="[12.8.3,)" />
		<ProjectReference Include="..\TableStorage\TableStorage.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="FluentTableEntity.cs">
			<DependentUpon>FluentTableEntity.tt</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
		<None Update="FluentTableEntity.tt">
			<LastGenOutput>FluentTableEntity.cs</LastGenOutput>
			<Generator>TextTemplatingFileGenerator</Generator>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="TableStorage.props" Pack="true" PackagePath="build\TableStorage.props" />
		<Using Include="Azure" />
		<Using Include="Azure.Data.Tables" />
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>
