<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="[12.8.3,)" />
		<ProjectReference Include="..\TableStorage\TableStorage.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TableStorage.Fluent.Extended" />
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="TableStorage.props" Pack="true" PackagePath="build\TableStorage.Fluent.props" />
		<Using Include="Azure" />
		<Using Include="Azure.Data.Tables" />
	</ItemGroup>

	<Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild">
		<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet t4 .\FluentTableEntity.tt -p ExtendedClasses=false" />
		<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet t4 .\Linq\FluentTableQueryHelper.tt -p ExtendedClasses=false" />
	</Target>
</Project>