<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="[12.8.3,)" />
		<ProjectReference Include="..\TableStorage\TableStorage.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="FluentTableEntity.tt">
			<LastGenOutput>FluentTableEntity.g.cs</LastGenOutput>
			<Generator>TextTemplatingFileGenerator</Generator>
		</None>
		<Compile Update="FluentTableEntity.g.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>FluentTableEntity.tt</DependentUpon>
		</Compile>
		<None Update="Linq\FluentTableQueryHelper.tt">
			<Generator>TextTemplatingFileGenerator</Generator>
			<LastGenOutput>FluentTableQueryHelper.g.cs</LastGenOutput>
		</None>
		<Compile Update="Linq\FluentTableQueryHelper.g.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>FluentTableQueryHelper.tt</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="TableStorage.props" Pack="true" PackagePath="build\TableStorage.props" />
		<Using Include="Azure" />
		<Using Include="Azure.Data.Tables" />
	</ItemGroup>

</Project>