<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>TableStorage</RootNamespace>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>

		<None Include="$(SolutionDir)\TableStorage.SourceGenerators\bin\$(Configuration)\$(TargetFramework)\TableStorage.SourceGenerators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

		<None Include="TableStorage.Core.props" Pack="true" PackagePath="build\TableStorage.Core.props" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TableStorage" />
		<InternalsVisibleTo Include="TableStorage.RuntimeCompilations" />
		<InternalsVisibleTo Include="TableStorage.Fluent" />
		<InternalsVisibleTo Include="TableStorage.Blobs" />
		<InternalsVisibleTo Include="TableStorage.Blobs.RuntimeCompilations" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="[8.0.0,)" />
	</ItemGroup>
</Project>
