<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<RootNamespace>TableStorage</RootNamespace>
		<VersionPrefix>$(MajorMinorVersion).$(BuildVersion)</VersionPrefix>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="TableStorage.Blobs.props" Pack="true" PackagePath="build\TableStorage.Blobs.props" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="[12.13.0,)" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="[8.0.0,)" />
		<PackageReference Include="System.Text.Json" Version="[8.0.5,)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TableStorage.Core\TableStorage.Core.csproj" PackageVersion="[^,$)" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TableStorage.Blobs.RuntimeCompilations" />
		<Using Include="Azure" />
		<Using Include="Azure.Storage.Blobs" />
		<Using Include="System.Text.Json" />
	</ItemGroup>
</Project>
