<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GeneratePackageOnBuild Condition="$(Configuration) == 'Release'">True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>TableStorage.png</PackageIcon>
		<VersionPrefix>$(MajorMinorVersion).0</VersionPrefix>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="TableStorage.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="TableStorage.props" Pack="true" PackagePath="build\TableStorage.props" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="*" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="[8.0.0,)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="[3.1.0, )" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[8.0.0, )" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TableStorage.RuntimeCompilations" />
		<InternalsVisibleTo Include="TableStorage.Fluent" />
		<InternalsVisibleTo Include="TableStorage.Fluent.Extended" />
		<ProjectReference Include="..\TableStorage.Core\TableStorage.Core.csproj" PackageVersion="[^,$)" />
		<Using Include="Azure" />
		<Using Include="Azure.Data.Tables" />
	</ItemGroup>
</Project>
